# Generated by Django 2.0.6 on 2018-07-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='sellerproduct',
            new_name='seller_product',
        ),
    ]
