# Generated by Django 2.0.6 on 2018-07-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180701_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_values', to='inventory.InventoryProduct'),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_values', to='inventory.ProductOptionValue'),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_values', to='inventory.InventoryProduct'),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_values', to='inventory.ProductVariant'),
        ),
    ]
