# Generated by Django 2.0.6 on 2018-07-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('asset', models.ImageField(blank=True, upload_to='ekozmp/static/img/site/designs/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='accounts.Profile')),
            ],
        ),
    ]
