# Generated by Django 2.0.6 on 2018-07-01 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
