# Generated by Django 2.0.6 on 2018-07-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20180701_1119'),
        ('designs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='inventory.ProductVariant')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='designs.Design')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='market.Shop'),
        ),
    ]
