# Generated by Django 2.0.6 on 2018-07-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180701_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='inventory.InventoryProduct'),
        ),
    ]
