# Generated by Django 2.0.6 on 2018-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180701_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='slug',
            field=models.SlugField(default='sellerproduct-slug', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='shop-slug', max_length=140),
            preserve_default=False,
        ),
    ]
